# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Kobe2016414
    driver-class-name: com.mysql.cj.jdbc.Driver